### PR TITLE
Feature locations on pd details locations filter 455

### LINKED ISSUE #455: Location filter on PD List and locations on Details Page
- [x] Add Locations to the PD Details page

 

- [x] Add Location filter (allowed to select multiple) to the Programme Document list Page

### PR DESCRIPTION
**Pull request by marcindo**
##### Feature list
* _Describe the list of features from Django_

* _Describe the list of features from Polymer_
- added multiple filter for locations on pd list
- added extra field to display locations on pd details screen

##### Progress checker
- [x] Django

- [x] Polymer

- [ ] Django test cases

- [ ] Polymer test cases

### CODE REVIEW

**Comment by rkrupinski** [comment]
@marcindo I made a couple of tweaks:

* Location formatting (they're objects w/ a `title` field)
* Column layout tweaks in pd filters
* Added locations to the PD/SSFA Details modal as it contains the same information
* Merged develop
* Some linter-related tweaks to make the app build

**Comment by chachra** [comment]
Thanks @rkrupinski 

Before we merge this @maciej-jaworski one additional thing came up. Can we make sure that the locations being used in the filter are only the ones that any of the PD's that this partner has have in them.

Meaning we should not be showing in filter all locations in db, just pertinent ones to this partner user (parter > pd's > locations), only unique set of all locations that this partners PD's might have.

**Comment by maciej-jaworski** [comment]
@chachra Location list comes from this endpoint:
https://github.com/unicef/etools-partner-reporting-portal/blob/feature-locations-on-pd-details-locations-filter-455/django_api/django_api/apps/unicef/views.py#L169

So filtering based on user and workspace seems to already be in place.

**Comment by chachra** [comment]
@n1207n Can you please review the backend portion of this PR since it has a lot of linting fixes etc. would like to get it in? tx.

**Pull request merged**
