### PR TITLE
[ch11170] Add ability to switch languages

### LINKED ISSUE #1120: Add ability to switch languages
Add a language switcher so that users can change to a different languages on the frontend for PRP.

### PR DESCRIPTION
**Pull request by AttilaTheHen**
##### Feature list
* _Describe the list of features from Polymer_
  * Add dropdown menu populated by locales.json keys
  * Connect dropdown menu to Redux in order to properly change state
  * Wrap appropriate keywords inside localize function and verify it works across components

##### Progress checker
- [x] Polymer

### CODE REVIEW

**Comment by AttilaTheHen** [comment]
Here's a quick gif of the switcher I made - just a simple dropdown menu:

languageSwitcher

**Comment by AttilaTheHen** [comment]
Sounds good!

**Comment by AttilaTheHen** [comment]
@n1207n Just updated the code to detect browser language. If no matching translation is available, it'll default to English.

**Comment by n1207n** [comment]
@AttilaTheHen, what about the previous localization code? Did you manage to merge or remove them?

**Comment by AttilaTheHen** [comment]
@n1207n Upon reviewing, I don't think I removed anything that Rafal had done. He set everything up to be able to use the localization behavior, and then I basically used his code to directly connect to a frontend component that I made (the dropdown).

The only part of Rafal's code that I had to touch at all was just that one line in the `localize.html` reducer to detect the browser language, instead of it being hardcoded to "en".

**Comment by n1207n** [comment]
Sounds great then. I'll be merging this.

**Pull request merged**
