### PR TITLE
Form validation response parameters and planned action #207

### PR DESCRIPTION
**Pull request by ErinOC**
Form validation for projects, activities, objectives creation #207 

+ Added _fieldsAreValid to utils behaviors to use it in multiple places

+ Changed date input component to use paper-date-picker 

+ Changed input components to just fetch the values for the dropdowns - not having the input fields as separate components simplified validation

+ Misc: Fixed a couple linter errors that I had missed in another branch

- [ ] Django

- [x] Polymer

- [ ] Django test cases

- [ ] Polymer test cases

### CODE REVIEW

**Comment by ErinOC** [comment]
"Status, Frequency of reporting and Total budget are not validated"  -- I didn't  validate those as required fields because they are not required by the API.   

@chachra Do we want all form fields in this mockup to be required fields?
 https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232532634

**Comment by ErinOC** [comment]
@rkrupinski I made the requested changes except for those related to dates. I'll wait until #222 is merged and re-use the date changes you made, and then ping you for another review.

**Comment by rkrupinski** [comment]
@ErinOC #222 is now merged.

**Comment by ErinOC** [comment]
@rkrupinski Changes are finished, please review.

**Pull request merged**
