### PR TITLE
Feature pd reports list#29

### PR DESCRIPTION
**Pull request by lkolacz**
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016132

- [x] Django API

- [x] Polymer

- [x] Django API test cases

- [ ] Polymer test cases

- [ ] Polymer test case for PD single detail page

### CODE REVIEW

**Comment by lkolacz** [comment]
fixing logical problems after merging this branch with develop

**Comment by n1207n** [comment]
Django side looks great. Polymer seems no drama as well.

There are few unit tests failed regarding ProgrammeDocument. After fixing those, Django should be looking good.

For Polymer side, unit test cases would be remaining items to check. ;)

**Comment by rkrupinski** [comment]
This blocks https://github.com/unicef/etools-partner-reporting-portal/issues/74

Do we plan to merge it anytime soon?

**Comment by n1207n** [comment]
Once Django and Polymer unit tests are good to go then we can merge. We need to enforce testability per PR now. Otherwise, we're keep carrying test cases to other PR.

**Comment by rkrupinski** [comment]
@adamtlord Please fix linter errors:

```

src/pages/app/ip-reporting/pd/pd-details.html_script_0.js
  line 62  col 42  requireSpaceBeforeBlockStatements: One (or more) spaces required before opening brace for block expressions
  line 62  col 42  requireSpacesInFunctionExpression: Missing space before opening curly brace
  line 63  col 10  requireSpaceAfterKeywords: One space required after "if" keyword
  line 63  col 20  requireSpaceBeforeBlockStatements: One (or more) spaces required before opening brace for block expressions
  line 70  col 15  Missing semicolon.
  line 70  col 13  requireSemicolons: Missing semicolon after statement

  ⚠  6 warnings


src/elements/ip-reporting/pd-reports-list.html_script_0.js
  line 42  col 27  requireSpaceBeforeBlockStatements: One (or more) spaces required before opening brace for block expressions
  line 42  col 10  requireSpaceAfterKeywords: One space required after "if" keyword
  line 43  col 24  requireSemicolons: Missing semicolon after statement
  line 43  col 31  Missing semicolon.
  line 44  col 50  Expected '===' and instead saw '=='.
  line 44  col 16  requireSpaceAfterKeywords: One space required after "if" keyword
  line 44  col 56  requireSpaceBeforeBlockStatements: One (or more) spaces required before opening brace for block expressions
  line 45  col 31  Missing semicolon.
  line 45  col 24  requireSemicolons: Missing semicolon after statement
  line 47  col 30  Missing semicolon.
  line 47  col 23  requireSemicolons: Missing semicolon after statement

  ⚠  11 warnings
```

**Comment by n1207n** [comment]
I'm gonna merge this branch soon. We'll have to carry Polymer test cases for PD single detail and  PD report list to other branch...

I understand testing environment for Polymer is not familiar with our expertise, but I hope to see codefresh testing for Polymer soon ;)

**Pull request merged**
