### PR TITLE
Feature - Indicator list filtering

### PR DESCRIPTION
**Pull request by n1207n**
This PR addresses a filtering option for Indicator List.

- [x] Django API

- [ ] Polymer

- [x] Django API test cases

- [ ] Polymer test cases

### CODE REVIEW

**Comment by chachra** [comment]
@n1207n please merge develop into them.

**Comment by rkrupinski** [comment]
@ErinOC See https://github.com/unicef/etools-partner-reporting-portal/issues/75

**Comment by ErinOC** [comment]
@rkrupinski This one should be good to go (other than testing, which I'm going to file a separate ticket for). I reused the three existing filters and added one to filter by PD. Clusters were in the mockups but weren't part of this ticket.  

I just saw the new checkbox filter; I'll add that in on Monday.

**Comment by rkrupinski** [comment]
@ErinOC Please pull from `develop`, then merge it to: `feature-indicator-list-#19` -> `feature-indicator-list-filtering-#20` and make sure pagination/filtering works with c6e7f2ebf831a322073a3750c8455d2d52467a48.

**Comment by ErinOC** [comment]
@rkrupinski I made the required pagination change and added the checkbox filter to the indicator filters component (I didn't merge your code in so the checkbox filter is going to 404 for now).

**Comment by rkrupinski** [comment]
> (I didn't merge your code in

@ErinOC Why?

**Comment by rkrupinski** [comment]
@n1207n @ErinOC 

Please, resolve conflicts so we could merge this:

```
both added:      ../django_api/django_api/apps/indicator/filters.py
both modified:   ../django_api/django_api/apps/indicator/models.py
both modified:   ../django_api/django_api/apps/indicator/serializers.py
both modified:   ../django_api/django_api/apps/indicator/tests/test_views.py
both modified:   ../django_api/django_api/apps/indicator/urls.py
both modified:   ../django_api/django_api/apps/indicator/views.py
both modified:   src/pages/app/ip-reporting/pd/pd-details.html
```

**Comment by ErinOC** [comment]
> @ErinOC Why?

I merged it into my branch temporarily for testing purposes, but didn't want to push it to the branch since you hadn't merged it into develop yet.

**Comment by rkrupinski** [comment]
It was actually meant to be merged to the filtering branch, bypassing develop:

https://github.com/unicef/etools-partner-reporting-portal/issues/75#issuecomment-305765683

**Pull request merged**
